### ISSUE TITLE
Chromecast connected, But no sound!

### ISSUE THREAD

**Issue by KevinLane09** [TroyFernandes/MusicBeeChromecast#18]
Hi Troy,

thank you for making this plugin available!

I installed the two files, set the port and ran the firewall configuration. When I click the Chromecast button in MusicBee, it shows my Chromecast devices, and when I select one, CCA gets connected But, My DAC says Error and no sound output is there from my System.

"Check status" says, Chromecast is connected and the server is running.

When I open the url http://localhost:8080/ on the PC running MusicBee, I see music file being streamed and an jpg.

OS is Windows 10 x64 

P.S. CCA+DAC works just fine from my Phone.

**Comment by KevinLane09** [comment]
CCA+DAC works just fine from my Phone.

**Comment by KevinLane09** [comment]
I can also see the streaming file in 192.168.1.X:8080 through my browser. But My DAC says error.

**Comment by KevinLane09** [comment]
It turns out Windows defender wasn't properly configured. I needed to go to "Windows Defender Firewall" -> "Allowed Apps" and enable both Public and Private access to "MusicBee Chromecast".

**Comment by Lharky** [comment]
> It turns out Windows defender wasn't properly configured. I needed to go to "Windows Defender Firewall" -> "Allowed Apps" and enable both Public and Private access to "MusicBee Chromecast".

How did add you "Musicbee Chromecast" to the list? It only lets me do Musicee by itself
