### ISSUE TITLE
Allowing pull requests?

### ISSUE THREAD

**Issue by sietsevdschoot** [TroyFernandes/MusicBeeChromecast#8]
Hi, 

When working through the codebase, I've created two branches for pull requests:

- Tidying up the ChromecastPanel code. Separating logic and presentation. Fixing the UI issue that only a small part of the chrome cast device name was visible in the panel.

- Added range check for port number in the console app.

Would you be interested in reviewing pull requests?

**Comment by TroyFernandes** [comment]
Sure, as long as it's code you've verified works I'm all for it. 

Edit: just wanna mention that I most likely won't be actively working on this plugin anymore until there's some new major thing I want to implement. Probably will only work on major bugs that appear. So for that reason you might want to fork the repo for your own use if you'd like.
